package com.app.compose_structure.model

import java.io.Serializable

data class FillCompInfoModel(
    val addr3: String? = null,
    val app: Any? = null,
    val addr4: String? = null,
    val addr1: String? = null,
    val addr2: String? = null,
    val compName: String? = null,
    val dfltOperTrfOut: String? = null,
    val weightVolume: Any? = null,
    val compId: String? = null,
    val connecting: Any? = null,
    val dfltOperTransitOut: String? = null,
    val sMTPPassword: Any? = null,
    val sMTPServerPort: Int? = null,
    val wSServerName: Any? = null,
    val custId: Any? = null,
    val phone: String? = null,
    val dfltOperTrfIn: String? = null,
    val sMTPServer: String? = null,
    val dfltOperIDIN: String? = null,
    val dfltOperIDOut: String? = null,
    val dfltBinCateg: Int? = null,
    val advancedServices: Boolean? = null,
    val wSReqMasterPass: String? = null,
    val sysCurr: String? = null,
    val mobile: String? = null,
    val roundingPrecision: Int? = null,
    val logo: String? = null,
    val wSConnecting: Any? = null,
    val retMsg: Any? = null,
    val baseCurr: String? = null,
    val dfltOperTransitIn: String? = null,
    val userId: Any? = null,
    val interfaceLanguage: Int? = null,
    val serverName: Any? = null,
    val volumePrecision: Int? = null,
    val myLocation: String? = null,
    val dBName: Any? = null,
    val dfltOperIDReturn: String? = null,
    val fax: String? = null,
    val wSDBName: Any? = null,
    val sMTPUserName: String? = null
) : Serializable
